# Racine de votre projet (à côté de package.json)
sonar.projectKey=nodeapp
sonar.projectName=Mon Application Node.js
sonar.projectVersion=1.0

# Chemin des fichiers sources (ajustez selon votre structure)
sonar.sources=src/
sonar.tests=test/

# Langage et configurations spécifiques
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions (fichiers à ignorer)
sonar.exclusions=node_modules/**, dist/**, coverage/**, **/*.spec.js
